# Obsidian Integration Configuration for POST TOOL
# This file defines the integration points between the POST TOOL project and the existing Obsidian vault

import os
from pathlib import Path

# Obsidian Vault Path
OBSIDIAN_VAULT_PATH = "/Users/dd/Library/Mobile Documents/iCloud~md~obsidian/Documents"

# POST TOOL Integration Paths within Obsidian Vault  
OBSIDIAN_POST_TOOL_ROOT = os.path.join(OBSIDIAN_VAULT_PATH, "00_POST_TOOL_Integration")
OBSIDIAN_AUTOMATED_INSIGHTS = os.path.join(OBSIDIAN_POST_TOOL_ROOT, "Automated_Insights") 

# Project Paths
PROJECT_ROOT = Path(__file__).parent
ARTICLES_PATH = PROJECT_ROOT / "articles"
BOOKS_PATH = PROJECT_ROOT / "books" 
AUTOMATION_PATH = PROJECT_ROOT / "automation"

# Git Repository Configuration
REPO_URL = "git@github.com:daideguchi/wisdom.git"
REPO_NAME = "wisdom"

# Integration Settings
INTEGRATION_CONFIG = {
    "obsidian_vault_path": OBSIDIAN_VAULT_PATH,
    "automated_insights_path": OBSIDIAN_AUTOMATED_INSIGHTS,
    "git_harvester_output": OBSIDIAN_AUTOMATED_INSIGHTS,
    "log_watcher_output": OBSIDIAN_AUTOMATED_INSIGHTS,
    "content_source_path": str(ARTICLES_PATH),
    "enable_icloud_sync": True,
    "ai_generated_prefix": "AI_GEN_",
    "status_tags": {
        "needs_review": "#status/needs-review",
        "in_progress": "#status/in-progress", 
        "completed": "#status/completed",
        "archived": "#status/archived"
    }
}

def get_obsidian_vault_path():
    """Return the Obsidian vault path"""
    return OBSIDIAN_VAULT_PATH

def get_automated_insights_path():
    """Return the automated insights folder path within Obsidian vault"""
    return OBSIDIAN_AUTOMATED_INSIGHTS

def ensure_integration_folders():
    """Ensure all necessary integration folders exist"""
    os.makedirs(OBSIDIAN_POST_TOOL_ROOT, exist_ok=True)
    os.makedirs(OBSIDIAN_AUTOMATED_INSIGHTS, exist_ok=True)
    
    # Create a README in the integration folder
    readme_path = os.path.join(OBSIDIAN_POST_TOOL_ROOT, "README.md")
    if not os.path.exists(readme_path):
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write("""# POST TOOL - Obsidian Integration

This folder contains automated content generated by the POST TOOL project.

## Structure
- `Automated_Insights/`: AI-generated notes from Git commits and log analysis
- `Content_Sync/`: Synced content from the main project
- `Dashboards/`: Dataview dashboards for managing generated content

## Usage
Generated notes will appear in `Automated_Insights/` with status tags:
- #status/needs-review: New notes requiring human review
- #status/in-progress: Notes being processed
- #status/completed: Processed and linked notes
- #status/archived: Old or irrelevant notes

Generated by POST TOOL automation system.
""")

if __name__ == "__main__":
    ensure_integration_folders()
    print("Obsidian integration folders created successfully!")